# Generated by Django 6.0 on 2025-12-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='retail_app__name_1d5363_idx'), models.Index(fields=['phone_number'], name='retail_app__phone_n_55727f_idx'), models.Index(fields=['region'], name='retail_app__region_faf95c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='retail_app__categor_d33baa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=64)),
                ('order_status', models.CharField(max_length=64)),
                ('delivery_type', models.CharField(max_length=64)),
                ('store_id', models.CharField(max_length=64)),
                ('store_location', models.CharField(max_length=128)),
                ('salesperson_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.product')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='retail_app__date_db98c4_idx'), models.Index(fields=['payment_method'], name='retail_app__payment_375dbc_idx')],
            },
        ),
    ]
