# Generated by Django 6.0 on 2025-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='retail_app.tag'),
        ),
    ]
